#! /bin/bash  -xue

script_dir=$(readlink -f $(dirname $0))
target_script='build.sh'

rm -f ${target_script}

time  ${script_dir}/configure ; echo $?

cat << __EOF__  | tee ${target_script}
#!/bin/bash  -xue

time  make && make -s check ; echo \$?
__EOF__

chmod 755 ${target_script}
