#! /bin/bash  -xue

script_dir=$(readlink -f "$(dirname "$0")")
build_script='build.sh'
rebuild_script='rebuild.sh'

rm -f "${build_script}" "${rebuild_script}"

time  "${script_dir}/configure" ; echo $?

cat << __EOF__  | tee "${build_script}"
#!/bin/bash  -xue

time  make && make -s check ; echo \$?
__EOF__

cat << __EOF__  | tee "${rebuild_script}"
#!/bin/bash  -xue

make clean
time  make && make -s check ; echo \$?
__EOF__

chmod 755 "${build_script}" "${rebuild_script}"
