#! /bin/bash  -xue

script_dir=$(readlink -f $(dirname $0))

time  ${script_dir}/configure ; echo $?

target_script='build.sh'

cat << __EOF__  | tee ${target_script}
#!/bin/bash  -xue

time  make && make -s check ; echo \$?
__EOF__

chmod  755  ${target_script}
